package com.lxzl.mybatis.bean;

public class Persion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persion.id
     *
     * @mbg.generated Fri Nov 02 17:13:37 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persion.name
     *
     * @mbg.generated Fri Nov 02 17:13:37 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persion.id
     *
     * @return the value of persion.id
     *
     * @mbg.generated Fri Nov 02 17:13:37 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persion.id
     *
     * @param id the value for persion.id
     *
     * @mbg.generated Fri Nov 02 17:13:37 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persion.name
     *
     * @return the value of persion.name
     *
     * @mbg.generated Fri Nov 02 17:13:37 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persion.name
     *
     * @param name the value for persion.name
     *
     * @mbg.generated Fri Nov 02 17:13:37 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}