package com.lxzl.db.bean;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of 公司画布信息表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Carouselinfo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID. */
	private Long caiid;

	/** 公司展示画布表. */
	private Carousel carousel;

	/** 图片路径. */
	private String imgUrl;

	/** 链接路径. */
	private String linkUrl;

	/** 优先级. */
	private Integer priority;

	/** 创建日期. */
	private Date createTime;

	/** 更新日期. */
	private Date updateTime;

	/**
	 * Constructor.
	 */
	public Carouselinfo() {
	}

	/**
	 * Set the ID.
	 * 
	 * @param caiid
	 *            ID
	 */
	public void setCaiid(Long caiid) {
		this.caiid = caiid;
	}

	/**
	 * Get the ID.
	 * 
	 * @return ID
	 */
	public Long getCaiid() {
		return this.caiid;
	}

	/**
	 * Set the 公司展示画布表.
	 * 
	 * @param carousel
	 *            公司展示画布表
	 */
	public void setCarousel(Carousel carousel) {
		this.carousel = carousel;
	}

	/**
	 * Get the 公司展示画布表.
	 * 
	 * @return 公司展示画布表
	 */
	public Carousel getCarousel() {
		return this.carousel;
	}

	/**
	 * Set the 图片路径.
	 * 
	 * @param imgUrl
	 *            图片路径
	 */
	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}

	/**
	 * Get the 图片路径.
	 * 
	 * @return 图片路径
	 */
	public String getImgUrl() {
		return this.imgUrl;
	}

	/**
	 * Set the 链接路径.
	 * 
	 * @param linkUrl
	 *            链接路径
	 */
	public void setLinkUrl(String linkUrl) {
		this.linkUrl = linkUrl;
	}

	/**
	 * Get the 链接路径.
	 * 
	 * @return 链接路径
	 */
	public String getLinkUrl() {
		return this.linkUrl;
	}

	/**
	 * Set the 优先级.
	 * 
	 * @param priority
	 *            优先级
	 */
	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	/**
	 * Get the 优先级.
	 * 
	 * @return 优先级
	 */
	public Integer getPriority() {
		return this.priority;
	}

	/**
	 * Set the 创建日期.
	 * 
	 * @param createTime
	 *            创建日期
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * Get the 创建日期.
	 * 
	 * @return 创建日期
	 */
	public Date getCreateTime() {
		return this.createTime;
	}

	/**
	 * Set the 更新日期.
	 * 
	 * @param updateTime
	 *            更新日期
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * Get the 更新日期.
	 * 
	 * @return 更新日期
	 */
	public Date getUpdateTime() {
		return this.updateTime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((caiid == null) ? 0 : caiid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Carouselinfo other = (Carouselinfo) obj;
		if (caiid == null) {
			if (other.caiid != null) {
				return false;
			}
		} else if (!caiid.equals(other.caiid)) {
			return false;
		}
		return true;
	}

}
