package com.cn.db.bean;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of 公司职工信息表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Companyemployeeinfo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID. */
	private Long ceiid;

	/** 职工信息表. */
	private Employee employee;

	/** 公司. */
	private Company company;

	/** 创建日期. */
	private Date createTime;

	/** 更新日期. */
	private Date updateTime;

	/**
	 * Constructor.
	 */
	public Companyemployeeinfo() {
	}

	/**
	 * Set the ID.
	 * 
	 * @param ceiid
	 *            ID
	 */
	public void setCeiid(Long ceiid) {
		this.ceiid = ceiid;
	}

	/**
	 * Get the ID.
	 * 
	 * @return ID
	 */
	public Long getCeiid() {
		return this.ceiid;
	}

	/**
	 * Set the 职工信息表.
	 * 
	 * @param employee
	 *            职工信息表
	 */
	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	/**
	 * Get the 职工信息表.
	 * 
	 * @return 职工信息表
	 */
	public Employee getEmployee() {
		return this.employee;
	}

	/**
	 * Set the 公司.
	 * 
	 * @param company
	 *            公司
	 */
	public void setCompany(Company company) {
		this.company = company;
	}

	/**
	 * Get the 公司.
	 * 
	 * @return 公司
	 */
	public Company getCompany() {
		return this.company;
	}

	/**
	 * Set the 创建日期.
	 * 
	 * @param createTime
	 *            创建日期
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * Get the 创建日期.
	 * 
	 * @return 创建日期
	 */
	public Date getCreateTime() {
		return this.createTime;
	}

	/**
	 * Set the 更新日期.
	 * 
	 * @param updateTime
	 *            更新日期
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * Get the 更新日期.
	 * 
	 * @return 更新日期
	 */
	public Date getUpdateTime() {
		return this.updateTime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((ceiid == null) ? 0 : ceiid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Companyemployeeinfo other = (Companyemployeeinfo) obj;
		if (ceiid == null) {
			if (other.ceiid != null) {
				return false;
			}
		} else if (!ceiid.equals(other.ceiid)) {
			return false;
		}
		return true;
	}

}
