package com.lxzl.db.bean;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of 证书表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Credential implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID. */
	private Long crid;

	/** 公司. */
	private Company company;

	/** 名称. */
	private String name;

	/** 图片路径. */
	private String imgUrl;

	/** 描述. */
	private String description;

	/** 到期日. */
	private Date endDate;

	/** 创建日期. */
	private Date createTime;

	/** 更新日期. */
	private Date updateTime;

	/**
	 * Constructor.
	 */
	public Credential() {
	}

	/**
	 * Set the ID.
	 * 
	 * @param crid
	 *            ID
	 */
	public void setCrid(Long crid) {
		this.crid = crid;
	}

	/**
	 * Get the ID.
	 * 
	 * @return ID
	 */
	public Long getCrid() {
		return this.crid;
	}

	/**
	 * Set the 公司.
	 * 
	 * @param company
	 *            公司
	 */
	public void setCompany(Company company) {
		this.company = company;
	}

	/**
	 * Get the 公司.
	 * 
	 * @return 公司
	 */
	public Company getCompany() {
		return this.company;
	}

	/**
	 * Set the 名称.
	 * 
	 * @param name
	 *            名称
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get the 名称.
	 * 
	 * @return 名称
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Set the 图片路径.
	 * 
	 * @param imgUrl
	 *            图片路径
	 */
	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}

	/**
	 * Get the 图片路径.
	 * 
	 * @return 图片路径
	 */
	public String getImgUrl() {
		return this.imgUrl;
	}

	/**
	 * Set the 描述.
	 * 
	 * @param description
	 *            描述
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * Get the 描述.
	 * 
	 * @return 描述
	 */
	public String getDescription() {
		return this.description;
	}

	/**
	 * Set the 到期日.
	 * 
	 * @param endDate
	 *            到期日
	 */
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	/**
	 * Get the 到期日.
	 * 
	 * @return 到期日
	 */
	public Date getEndDate() {
		return this.endDate;
	}

	/**
	 * Set the 创建日期.
	 * 
	 * @param createTime
	 *            创建日期
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * Get the 创建日期.
	 * 
	 * @return 创建日期
	 */
	public Date getCreateTime() {
		return this.createTime;
	}

	/**
	 * Set the 更新日期.
	 * 
	 * @param updateTime
	 *            更新日期
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * Get the 更新日期.
	 * 
	 * @return 更新日期
	 */
	public Date getUpdateTime() {
		return this.updateTime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((crid == null) ? 0 : crid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Credential other = (Credential) obj;
		if (crid == null) {
			if (other.crid != null) {
				return false;
			}
		} else if (!crid.equals(other.crid)) {
			return false;
		}
		return true;
	}

}
