package com.cn.db.bean;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of CustomerInfo.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Customerinfo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID. */
	private Long ciid;

	/** 用户信息表. */
	private Customer customer;

	/** 别名. */
	private String aliasName;

	/** 密码. */
	private String password;

	/** 手机号. */
	private String phone;

	/** 邮箱. */
	private String email;

	/** 创建日期. */
	private Date createTime;

	/** 更新日期. */
	private Date updateTime;

	/**
	 * Constructor.
	 */
	public Customerinfo() {
	}

	/**
	 * Set the ID.
	 * 
	 * @param ciid
	 *            ID
	 */
	public void setCiid(Long ciid) {
		this.ciid = ciid;
	}

	/**
	 * Get the ID.
	 * 
	 * @return ID
	 */
	public Long getCiid() {
		return this.ciid;
	}

	/**
	 * Set the 用户信息表.
	 * 
	 * @param customer
	 *            用户信息表
	 */
	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	/**
	 * Get the 用户信息表.
	 * 
	 * @return 用户信息表
	 */
	public Customer getCustomer() {
		return this.customer;
	}

	/**
	 * Set the 别名.
	 * 
	 * @param aliasName
	 *            别名
	 */
	public void setAliasName(String aliasName) {
		this.aliasName = aliasName;
	}

	/**
	 * Get the 别名.
	 * 
	 * @return 别名
	 */
	public String getAliasName() {
		return this.aliasName;
	}

	/**
	 * Set the 密码.
	 * 
	 * @param password
	 *            密码
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * Get the 密码.
	 * 
	 * @return 密码
	 */
	public String getPassword() {
		return this.password;
	}

	/**
	 * Set the 手机号.
	 * 
	 * @param phone
	 *            手机号
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * Get the 手机号.
	 * 
	 * @return 手机号
	 */
	public String getPhone() {
		return this.phone;
	}

	/**
	 * Set the 邮箱.
	 * 
	 * @param email
	 *            邮箱
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * Get the 邮箱.
	 * 
	 * @return 邮箱
	 */
	public String getEmail() {
		return this.email;
	}

	/**
	 * Set the 创建日期.
	 * 
	 * @param createTime
	 *            创建日期
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * Get the 创建日期.
	 * 
	 * @return 创建日期
	 */
	public Date getCreateTime() {
		return this.createTime;
	}

	/**
	 * Set the 更新日期.
	 * 
	 * @param updateTime
	 *            更新日期
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * Get the 更新日期.
	 * 
	 * @return 更新日期
	 */
	public Date getUpdateTime() {
		return this.updateTime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((ciid == null) ? 0 : ciid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Customerinfo other = (Customerinfo) obj;
		if (ciid == null) {
			if (other.ciid != null) {
				return false;
			}
		} else if (!ciid.equals(other.ciid)) {
			return false;
		}
		return true;
	}

}
