package com.cn.db.bean;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of 公司客户信息表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Customercompanyinfo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID. */
	private Long cciid;

	/** 用户信息表. */
	private Customer customer;

	/** 公司. */
	private Company company;

	/** 创建日期. */
	private Date createTime;

	/** 更新日期. */
	private Date updateTime;

	/**
	 * Constructor.
	 */
	public Customercompanyinfo() {
	}

	/**
	 * Set the ID.
	 * 
	 * @param cciid
	 *            ID
	 */
	public void setCciid(Long cciid) {
		this.cciid = cciid;
	}

	/**
	 * Get the ID.
	 * 
	 * @return ID
	 */
	public Long getCciid() {
		return this.cciid;
	}

	/**
	 * Set the 用户信息表.
	 * 
	 * @param customer
	 *            用户信息表
	 */
	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	/**
	 * Get the 用户信息表.
	 * 
	 * @return 用户信息表
	 */
	public Customer getCustomer() {
		return this.customer;
	}

	/**
	 * Set the 公司.
	 * 
	 * @param company
	 *            公司
	 */
	public void setCompany(Company company) {
		this.company = company;
	}

	/**
	 * Get the 公司.
	 * 
	 * @return 公司
	 */
	public Company getCompany() {
		return this.company;
	}

	/**
	 * Set the 创建日期.
	 * 
	 * @param createTime
	 *            创建日期
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * Get the 创建日期.
	 * 
	 * @return 创建日期
	 */
	public Date getCreateTime() {
		return this.createTime;
	}

	/**
	 * Set the 更新日期.
	 * 
	 * @param updateTime
	 *            更新日期
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * Get the 更新日期.
	 * 
	 * @return 更新日期
	 */
	public Date getUpdateTime() {
		return this.updateTime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((cciid == null) ? 0 : cciid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Customercompanyinfo other = (Customercompanyinfo) obj;
		if (cciid == null) {
			if (other.cciid != null) {
				return false;
			}
		} else if (!cciid.equals(other.cciid)) {
			return false;
		}
		return true;
	}

}
