package com.cn.db.bean;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of 用户级别.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Customerlevel implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID. */
	private Long clid;

	/** 标识. */
	private Integer level;

	/** 名称. */
	private String name;

	/** 创建日期. */
	private Date createTime;

	/** 更新日期. */
	private Date updateTime;

	/** The set of 用户信息表. */
	private Set<Customerlevelinfo> customerlevelinfoSet;

	/**
	 * Constructor.
	 */
	public Customerlevel() {
		this.customerlevelinfoSet = new HashSet<Customerlevelinfo>();
	}

	/**
	 * Set the ID.
	 * 
	 * @param clid
	 *            ID
	 */
	public void setClid(Long clid) {
		this.clid = clid;
	}

	/**
	 * Get the ID.
	 * 
	 * @return ID
	 */
	public Long getClid() {
		return this.clid;
	}

	/**
	 * Set the 标识.
	 * 
	 * @param level
	 *            标识
	 */
	public void setLevel(Integer level) {
		this.level = level;
	}

	/**
	 * Get the 标识.
	 * 
	 * @return 标识
	 */
	public Integer getLevel() {
		return this.level;
	}

	/**
	 * Set the 名称.
	 * 
	 * @param name
	 *            名称
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get the 名称.
	 * 
	 * @return 名称
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Set the 创建日期.
	 * 
	 * @param createTime
	 *            创建日期
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * Get the 创建日期.
	 * 
	 * @return 创建日期
	 */
	public Date getCreateTime() {
		return this.createTime;
	}

	/**
	 * Set the 更新日期.
	 * 
	 * @param updateTime
	 *            更新日期
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * Get the 更新日期.
	 * 
	 * @return 更新日期
	 */
	public Date getUpdateTime() {
		return this.updateTime;
	}

	/**
	 * Set the set of the 用户信息表.
	 * 
	 * @param customerlevelinfoSet
	 *            The set of 用户信息表
	 */
	public void setCustomerlevelinfoSet(Set<Customerlevelinfo> customerlevelinfoSet) {
		this.customerlevelinfoSet = customerlevelinfoSet;
	}

	/**
	 * Add the 用户信息表.
	 * 
	 * @param customerlevelinfo
	 *            用户信息表
	 */
	public void addCustomerlevelinfo(Customerlevelinfo customerlevelinfo) {
		this.customerlevelinfoSet.add(customerlevelinfo);
	}

	/**
	 * Get the set of the 用户信息表.
	 * 
	 * @return The set of 用户信息表
	 */
	public Set<Customerlevelinfo> getCustomerlevelinfoSet() {
		return this.customerlevelinfoSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((clid == null) ? 0 : clid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Customerlevel other = (Customerlevel) obj;
		if (clid == null) {
			if (other.clid != null) {
				return false;
			}
		} else if (!clid.equals(other.clid)) {
			return false;
		}
		return true;
	}

}
