package com.cn.db.bean;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of 评价等级表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Customerestimatelevel implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID. */
	private Long celid;

	/** 分数. */
	private Long grade;

	/** 类型. */
	private String type;

	/** 创建日期. */
	private Date createTime;

	/** 更新日期. */
	private Date updateTime;

	/** The set of 用户评价表. */
	private Set<Customerestimateinfo> customerestimateinfoSet;

	/**
	 * Constructor.
	 */
	public Customerestimatelevel() {
		this.customerestimateinfoSet = new HashSet<Customerestimateinfo>();
	}

	/**
	 * Set the ID.
	 * 
	 * @param celid
	 *            ID
	 */
	public void setCelid(Long celid) {
		this.celid = celid;
	}

	/**
	 * Get the ID.
	 * 
	 * @return ID
	 */
	public Long getCelid() {
		return this.celid;
	}

	/**
	 * Set the 分数.
	 * 
	 * @param grade
	 *            分数
	 */
	public void setGrade(Long grade) {
		this.grade = grade;
	}

	/**
	 * Get the 分数.
	 * 
	 * @return 分数
	 */
	public Long getGrade() {
		return this.grade;
	}

	/**
	 * Set the 类型.
	 * 
	 * @param type
	 *            类型
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * Get the 类型.
	 * 
	 * @return 类型
	 */
	public String getType() {
		return this.type;
	}

	/**
	 * Set the 创建日期.
	 * 
	 * @param createTime
	 *            创建日期
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * Get the 创建日期.
	 * 
	 * @return 创建日期
	 */
	public Date getCreateTime() {
		return this.createTime;
	}

	/**
	 * Set the 更新日期.
	 * 
	 * @param updateTime
	 *            更新日期
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * Get the 更新日期.
	 * 
	 * @return 更新日期
	 */
	public Date getUpdateTime() {
		return this.updateTime;
	}

	/**
	 * Set the set of the 用户评价表.
	 * 
	 * @param customerestimateinfoSet
	 *            The set of 用户评价表
	 */
	public void setCustomerestimateinfoSet(Set<Customerestimateinfo> customerestimateinfoSet) {
		this.customerestimateinfoSet = customerestimateinfoSet;
	}

	/**
	 * Add the 用户评价表.
	 * 
	 * @param customerestimateinfo
	 *            用户评价表
	 */
	public void addCustomerestimateinfo(Customerestimateinfo customerestimateinfo) {
		this.customerestimateinfoSet.add(customerestimateinfo);
	}

	/**
	 * Get the set of the 用户评价表.
	 * 
	 * @return The set of 用户评价表
	 */
	public Set<Customerestimateinfo> getCustomerestimateinfoSet() {
		return this.customerestimateinfoSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((celid == null) ? 0 : celid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Customerestimatelevel other = (Customerestimatelevel) obj;
		if (celid == null) {
			if (other.celid != null) {
				return false;
			}
		} else if (!celid.equals(other.celid)) {
			return false;
		}
		return true;
	}

}
