package com.cn.db.bean;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of 用户信息表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Customer implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 用户ID. */
	private Long cid;

	/** 名称. */
	private String name;

	/** 年龄. */
	private Short age;

	/** 性别. */
	private String sex;

	/** 创建日期. */
	private Date createTime;

	/** 更新日期. */
	private Date updateTime;

	/** The set of 公司客户信息表. */
	private Set<Customercompanyinfo> customercompanyinfoSet;

	/** The set of 用户评价表. */
	private Set<Customerestimateinfo> customerestimateinfoSet;

	/** The set of CustomerInfo. */
	private Set<Customerinfo> customerinfoSet;

	/** The set of 用户信息表. */
	private Set<Customerlevelinfo> customerlevelinfoSet;

	/**
	 * Constructor.
	 */
	public Customer() {
		this.customercompanyinfoSet = new HashSet<Customercompanyinfo>();
		this.customerestimateinfoSet = new HashSet<Customerestimateinfo>();
		this.customerinfoSet = new HashSet<Customerinfo>();
		this.customerlevelinfoSet = new HashSet<Customerlevelinfo>();
	}

	/**
	 * Set the 用户ID.
	 * 
	 * @param cid
	 *            用户ID
	 */
	public void setCid(Long cid) {
		this.cid = cid;
	}

	/**
	 * Get the 用户ID.
	 * 
	 * @return 用户ID
	 */
	public Long getCid() {
		return this.cid;
	}

	/**
	 * Set the 名称.
	 * 
	 * @param name
	 *            名称
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get the 名称.
	 * 
	 * @return 名称
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Set the 年龄.
	 * 
	 * @param age
	 *            年龄
	 */
	public void setAge(Short age) {
		this.age = age;
	}

	/**
	 * Get the 年龄.
	 * 
	 * @return 年龄
	 */
	public Short getAge() {
		return this.age;
	}

	/**
	 * Set the 性别.
	 * 
	 * @param sex
	 *            性别
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * Get the 性别.
	 * 
	 * @return 性别
	 */
	public String getSex() {
		return this.sex;
	}

	/**
	 * Set the 创建日期.
	 * 
	 * @param createTime
	 *            创建日期
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * Get the 创建日期.
	 * 
	 * @return 创建日期
	 */
	public Date getCreateTime() {
		return this.createTime;
	}

	/**
	 * Set the 更新日期.
	 * 
	 * @param updateTime
	 *            更新日期
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * Get the 更新日期.
	 * 
	 * @return 更新日期
	 */
	public Date getUpdateTime() {
		return this.updateTime;
	}

	/**
	 * Set the set of the 公司客户信息表.
	 * 
	 * @param customercompanyinfoSet
	 *            The set of 公司客户信息表
	 */
	public void setCustomercompanyinfoSet(Set<Customercompanyinfo> customercompanyinfoSet) {
		this.customercompanyinfoSet = customercompanyinfoSet;
	}

	/**
	 * Add the 公司客户信息表.
	 * 
	 * @param customercompanyinfo
	 *            公司客户信息表
	 */
	public void addCustomercompanyinfo(Customercompanyinfo customercompanyinfo) {
		this.customercompanyinfoSet.add(customercompanyinfo);
	}

	/**
	 * Get the set of the 公司客户信息表.
	 * 
	 * @return The set of 公司客户信息表
	 */
	public Set<Customercompanyinfo> getCustomercompanyinfoSet() {
		return this.customercompanyinfoSet;
	}

	/**
	 * Set the set of the 用户评价表.
	 * 
	 * @param customerestimateinfoSet
	 *            The set of 用户评价表
	 */
	public void setCustomerestimateinfoSet(Set<Customerestimateinfo> customerestimateinfoSet) {
		this.customerestimateinfoSet = customerestimateinfoSet;
	}

	/**
	 * Add the 用户评价表.
	 * 
	 * @param customerestimateinfo
	 *            用户评价表
	 */
	public void addCustomerestimateinfo(Customerestimateinfo customerestimateinfo) {
		this.customerestimateinfoSet.add(customerestimateinfo);
	}

	/**
	 * Get the set of the 用户评价表.
	 * 
	 * @return The set of 用户评价表
	 */
	public Set<Customerestimateinfo> getCustomerestimateinfoSet() {
		return this.customerestimateinfoSet;
	}

	/**
	 * Set the set of the CustomerInfo.
	 * 
	 * @param customerinfoSet
	 *            The set of CustomerInfo
	 */
	public void setCustomerinfoSet(Set<Customerinfo> customerinfoSet) {
		this.customerinfoSet = customerinfoSet;
	}

	/**
	 * Add the CustomerInfo.
	 * 
	 * @param customerinfo
	 *            CustomerInfo
	 */
	public void addCustomerinfo(Customerinfo customerinfo) {
		this.customerinfoSet.add(customerinfo);
	}

	/**
	 * Get the set of the CustomerInfo.
	 * 
	 * @return The set of CustomerInfo
	 */
	public Set<Customerinfo> getCustomerinfoSet() {
		return this.customerinfoSet;
	}

	/**
	 * Set the set of the 用户信息表.
	 * 
	 * @param customerlevelinfoSet
	 *            The set of 用户信息表
	 */
	public void setCustomerlevelinfoSet(Set<Customerlevelinfo> customerlevelinfoSet) {
		this.customerlevelinfoSet = customerlevelinfoSet;
	}

	/**
	 * Add the 用户信息表.
	 * 
	 * @param customerlevelinfo
	 *            用户信息表
	 */
	public void addCustomerlevelinfo(Customerlevelinfo customerlevelinfo) {
		this.customerlevelinfoSet.add(customerlevelinfo);
	}

	/**
	 * Get the set of the 用户信息表.
	 * 
	 * @return The set of 用户信息表
	 */
	public Set<Customerlevelinfo> getCustomerlevelinfoSet() {
		return this.customerlevelinfoSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((cid == null) ? 0 : cid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Customer other = (Customer) obj;
		if (cid == null) {
			if (other.cid != null) {
				return false;
			}
		} else if (!cid.equals(other.cid)) {
			return false;
		}
		return true;
	}

}
