package com.cn.db.bean;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of 员工级别信息表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Employeelevelinfo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID. */
	private Long eliid;

	/** 员工级别表. */
	private Employeelevel employeelevel;

	/** 职工信息表. */
	private Employee employee;

	/** 创建日期. */
	private Date createTime;

	/** 更新日期. */
	private Date updateTime;

	/**
	 * Constructor.
	 */
	public Employeelevelinfo() {
	}

	/**
	 * Set the ID.
	 * 
	 * @param eliid
	 *            ID
	 */
	public void setEliid(Long eliid) {
		this.eliid = eliid;
	}

	/**
	 * Get the ID.
	 * 
	 * @return ID
	 */
	public Long getEliid() {
		return this.eliid;
	}

	/**
	 * Set the 员工级别表.
	 * 
	 * @param employeelevel
	 *            员工级别表
	 */
	public void setEmployeelevel(Employeelevel employeelevel) {
		this.employeelevel = employeelevel;
	}

	/**
	 * Get the 员工级别表.
	 * 
	 * @return 员工级别表
	 */
	public Employeelevel getEmployeelevel() {
		return this.employeelevel;
	}

	/**
	 * Set the 职工信息表.
	 * 
	 * @param employee
	 *            职工信息表
	 */
	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	/**
	 * Get the 职工信息表.
	 * 
	 * @return 职工信息表
	 */
	public Employee getEmployee() {
		return this.employee;
	}

	/**
	 * Set the 创建日期.
	 * 
	 * @param createTime
	 *            创建日期
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * Get the 创建日期.
	 * 
	 * @return 创建日期
	 */
	public Date getCreateTime() {
		return this.createTime;
	}

	/**
	 * Set the 更新日期.
	 * 
	 * @param updateTime
	 *            更新日期
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * Get the 更新日期.
	 * 
	 * @return 更新日期
	 */
	public Date getUpdateTime() {
		return this.updateTime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((eliid == null) ? 0 : eliid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Employeelevelinfo other = (Employeelevelinfo) obj;
		if (eliid == null) {
			if (other.eliid != null) {
				return false;
			}
		} else if (!eliid.equals(other.eliid)) {
			return false;
		}
		return true;
	}

}
