package com.cn.db.bean;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of 职工信息表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Employee implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID. */
	private Long edi;

	/** 姓名. */
	private String name;

	/** 年龄. */
	private Integer age;

	/** 性别. */
	private String sex;

	/** 创建日期. */
	private Date createTime;

	/** 更新日期. */
	private Date updateTime;

	/** The set of 公司职工信息表. */
	private Set<Companyemployeeinfo> companyemployeeinfoSet;

	/** The set of EmployeeInfo. */
	private Set<Employeeinfo> employeeinfoSet;

	/** The set of 员工级别信息表. */
	private Set<Employeelevelinfo> employeelevelinfoSet;

	/** The set of 职工状态信息表. */
	private Set<Employeestatusinfo> employeestatusinfoSet;

	/** The set of 项目职工信息表. */
	private Set<Projectemployeeinfo> projectemployeeinfoSet;

	/**
	 * Constructor.
	 */
	public Employee() {
		this.companyemployeeinfoSet = new HashSet<Companyemployeeinfo>();
		this.employeeinfoSet = new HashSet<Employeeinfo>();
		this.employeelevelinfoSet = new HashSet<Employeelevelinfo>();
		this.employeestatusinfoSet = new HashSet<Employeestatusinfo>();
		this.projectemployeeinfoSet = new HashSet<Projectemployeeinfo>();
	}

	/**
	 * Set the ID.
	 * 
	 * @param edi
	 *            ID
	 */
	public void setEdi(Long edi) {
		this.edi = edi;
	}

	/**
	 * Get the ID.
	 * 
	 * @return ID
	 */
	public Long getEdi() {
		return this.edi;
	}

	/**
	 * Set the 姓名.
	 * 
	 * @param name
	 *            姓名
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get the 姓名.
	 * 
	 * @return 姓名
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Set the 年龄.
	 * 
	 * @param age
	 *            年龄
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * Get the 年龄.
	 * 
	 * @return 年龄
	 */
	public Integer getAge() {
		return this.age;
	}

	/**
	 * Set the 性别.
	 * 
	 * @param sex
	 *            性别
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * Get the 性别.
	 * 
	 * @return 性别
	 */
	public String getSex() {
		return this.sex;
	}

	/**
	 * Set the 创建日期.
	 * 
	 * @param createTime
	 *            创建日期
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * Get the 创建日期.
	 * 
	 * @return 创建日期
	 */
	public Date getCreateTime() {
		return this.createTime;
	}

	/**
	 * Set the 更新日期.
	 * 
	 * @param updateTime
	 *            更新日期
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * Get the 更新日期.
	 * 
	 * @return 更新日期
	 */
	public Date getUpdateTime() {
		return this.updateTime;
	}

	/**
	 * Set the set of the 公司职工信息表.
	 * 
	 * @param companyemployeeinfoSet
	 *            The set of 公司职工信息表
	 */
	public void setCompanyemployeeinfoSet(Set<Companyemployeeinfo> companyemployeeinfoSet) {
		this.companyemployeeinfoSet = companyemployeeinfoSet;
	}

	/**
	 * Add the 公司职工信息表.
	 * 
	 * @param companyemployeeinfo
	 *            公司职工信息表
	 */
	public void addCompanyemployeeinfo(Companyemployeeinfo companyemployeeinfo) {
		this.companyemployeeinfoSet.add(companyemployeeinfo);
	}

	/**
	 * Get the set of the 公司职工信息表.
	 * 
	 * @return The set of 公司职工信息表
	 */
	public Set<Companyemployeeinfo> getCompanyemployeeinfoSet() {
		return this.companyemployeeinfoSet;
	}

	/**
	 * Set the set of the EmployeeInfo.
	 * 
	 * @param employeeinfoSet
	 *            The set of EmployeeInfo
	 */
	public void setEmployeeinfoSet(Set<Employeeinfo> employeeinfoSet) {
		this.employeeinfoSet = employeeinfoSet;
	}

	/**
	 * Add the EmployeeInfo.
	 * 
	 * @param employeeinfo
	 *            EmployeeInfo
	 */
	public void addEmployeeinfo(Employeeinfo employeeinfo) {
		this.employeeinfoSet.add(employeeinfo);
	}

	/**
	 * Get the set of the EmployeeInfo.
	 * 
	 * @return The set of EmployeeInfo
	 */
	public Set<Employeeinfo> getEmployeeinfoSet() {
		return this.employeeinfoSet;
	}

	/**
	 * Set the set of the 员工级别信息表.
	 * 
	 * @param employeelevelinfoSet
	 *            The set of 员工级别信息表
	 */
	public void setEmployeelevelinfoSet(Set<Employeelevelinfo> employeelevelinfoSet) {
		this.employeelevelinfoSet = employeelevelinfoSet;
	}

	/**
	 * Add the 员工级别信息表.
	 * 
	 * @param employeelevelinfo
	 *            员工级别信息表
	 */
	public void addEmployeelevelinfo(Employeelevelinfo employeelevelinfo) {
		this.employeelevelinfoSet.add(employeelevelinfo);
	}

	/**
	 * Get the set of the 员工级别信息表.
	 * 
	 * @return The set of 员工级别信息表
	 */
	public Set<Employeelevelinfo> getEmployeelevelinfoSet() {
		return this.employeelevelinfoSet;
	}

	/**
	 * Set the set of the 职工状态信息表.
	 * 
	 * @param employeestatusinfoSet
	 *            The set of 职工状态信息表
	 */
	public void setEmployeestatusinfoSet(Set<Employeestatusinfo> employeestatusinfoSet) {
		this.employeestatusinfoSet = employeestatusinfoSet;
	}

	/**
	 * Add the 职工状态信息表.
	 * 
	 * @param employeestatusinfo
	 *            职工状态信息表
	 */
	public void addEmployeestatusinfo(Employeestatusinfo employeestatusinfo) {
		this.employeestatusinfoSet.add(employeestatusinfo);
	}

	/**
	 * Get the set of the 职工状态信息表.
	 * 
	 * @return The set of 职工状态信息表
	 */
	public Set<Employeestatusinfo> getEmployeestatusinfoSet() {
		return this.employeestatusinfoSet;
	}

	/**
	 * Set the set of the 项目职工信息表.
	 * 
	 * @param projectemployeeinfoSet
	 *            The set of 项目职工信息表
	 */
	public void setProjectemployeeinfoSet(Set<Projectemployeeinfo> projectemployeeinfoSet) {
		this.projectemployeeinfoSet = projectemployeeinfoSet;
	}

	/**
	 * Add the 项目职工信息表.
	 * 
	 * @param projectemployeeinfo
	 *            项目职工信息表
	 */
	public void addProjectemployeeinfo(Projectemployeeinfo projectemployeeinfo) {
		this.projectemployeeinfoSet.add(projectemployeeinfo);
	}

	/**
	 * Get the set of the 项目职工信息表.
	 * 
	 * @return The set of 项目职工信息表
	 */
	public Set<Projectemployeeinfo> getProjectemployeeinfoSet() {
		return this.projectemployeeinfoSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((edi == null) ? 0 : edi.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Employee other = (Employee) obj;
		if (edi == null) {
			if (other.edi != null) {
				return false;
			}
		} else if (!edi.equals(other.edi)) {
			return false;
		}
		return true;
	}

}
