package com.cn.db.bean;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of 员工级别表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Employeelevel implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID. */
	private Long elid;

	/** 级别. */
	private String level;

	/** 名称. */
	private String name;

	/** 创建日期. */
	private Date createTime;

	/** 更新日期. */
	private Date updateTime;

	/** The set of 员工级别信息表. */
	private Set<Employeelevelinfo> employeelevelinfoSet;

	/**
	 * Constructor.
	 */
	public Employeelevel() {
		this.employeelevelinfoSet = new HashSet<Employeelevelinfo>();
	}

	/**
	 * Set the ID.
	 * 
	 * @param elid
	 *            ID
	 */
	public void setElid(Long elid) {
		this.elid = elid;
	}

	/**
	 * Get the ID.
	 * 
	 * @return ID
	 */
	public Long getElid() {
		return this.elid;
	}

	/**
	 * Set the 级别.
	 * 
	 * @param level
	 *            级别
	 */
	public void setLevel(String level) {
		this.level = level;
	}

	/**
	 * Get the 级别.
	 * 
	 * @return 级别
	 */
	public String getLevel() {
		return this.level;
	}

	/**
	 * Set the 名称.
	 * 
	 * @param name
	 *            名称
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get the 名称.
	 * 
	 * @return 名称
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Set the 创建日期.
	 * 
	 * @param createTime
	 *            创建日期
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * Get the 创建日期.
	 * 
	 * @return 创建日期
	 */
	public Date getCreateTime() {
		return this.createTime;
	}

	/**
	 * Set the 更新日期.
	 * 
	 * @param updateTime
	 *            更新日期
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * Get the 更新日期.
	 * 
	 * @return 更新日期
	 */
	public Date getUpdateTime() {
		return this.updateTime;
	}

	/**
	 * Set the set of the 员工级别信息表.
	 * 
	 * @param employeelevelinfoSet
	 *            The set of 员工级别信息表
	 */
	public void setEmployeelevelinfoSet(Set<Employeelevelinfo> employeelevelinfoSet) {
		this.employeelevelinfoSet = employeelevelinfoSet;
	}

	/**
	 * Add the 员工级别信息表.
	 * 
	 * @param employeelevelinfo
	 *            员工级别信息表
	 */
	public void addEmployeelevelinfo(Employeelevelinfo employeelevelinfo) {
		this.employeelevelinfoSet.add(employeelevelinfo);
	}

	/**
	 * Get the set of the 员工级别信息表.
	 * 
	 * @return The set of 员工级别信息表
	 */
	public Set<Employeelevelinfo> getEmployeelevelinfoSet() {
		return this.employeelevelinfoSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((elid == null) ? 0 : elid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Employeelevel other = (Employeelevel) obj;
		if (elid == null) {
			if (other.elid != null) {
				return false;
			}
		} else if (!elid.equals(other.elid)) {
			return false;
		}
		return true;
	}

}
