package com.cn.db.bean;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of 职工状态信息表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Employeestatusinfo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID. */
	private Long esiid;

	/** 职工状态表. */
	private Employeestatus employeestatus;

	/** 职工信息表. */
	private Employee employee;

	/** 创建日期. */
	private Date createTime;

	/** 更新日期. */
	private Date updateTime;

	/**
	 * Constructor.
	 */
	public Employeestatusinfo() {
	}

	/**
	 * Set the ID.
	 * 
	 * @param esiid
	 *            ID
	 */
	public void setEsiid(Long esiid) {
		this.esiid = esiid;
	}

	/**
	 * Get the ID.
	 * 
	 * @return ID
	 */
	public Long getEsiid() {
		return this.esiid;
	}

	/**
	 * Set the 职工状态表.
	 * 
	 * @param employeestatus
	 *            职工状态表
	 */
	public void setEmployeestatus(Employeestatus employeestatus) {
		this.employeestatus = employeestatus;
	}

	/**
	 * Get the 职工状态表.
	 * 
	 * @return 职工状态表
	 */
	public Employeestatus getEmployeestatus() {
		return this.employeestatus;
	}

	/**
	 * Set the 职工信息表.
	 * 
	 * @param employee
	 *            职工信息表
	 */
	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	/**
	 * Get the 职工信息表.
	 * 
	 * @return 职工信息表
	 */
	public Employee getEmployee() {
		return this.employee;
	}

	/**
	 * Set the 创建日期.
	 * 
	 * @param createTime
	 *            创建日期
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * Get the 创建日期.
	 * 
	 * @return 创建日期
	 */
	public Date getCreateTime() {
		return this.createTime;
	}

	/**
	 * Set the 更新日期.
	 * 
	 * @param updateTime
	 *            更新日期
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * Get the 更新日期.
	 * 
	 * @return 更新日期
	 */
	public Date getUpdateTime() {
		return this.updateTime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((esiid == null) ? 0 : esiid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Employeestatusinfo other = (Employeestatusinfo) obj;
		if (esiid == null) {
			if (other.esiid != null) {
				return false;
			}
		} else if (!esiid.equals(other.esiid)) {
			return false;
		}
		return true;
	}

}
