package com.lxzl.db.bean;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of 新闻表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class News implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID. */
	private Long nid;

	/** 公司. */
	private Company company;

	/** 标题. */
	private String title;

	/** description. */
	private String description;

	/** 创建日期. */
	private Date createTime;

	/** 更新日期. */
	private Date updateTime;

	/** The set of 新闻详细表. */
	private Set<Newsinfo> newsinfoSet;

	/**
	 * Constructor.
	 */
	public News() {
		this.newsinfoSet = new HashSet<Newsinfo>();
	}

	/**
	 * Set the ID.
	 * 
	 * @param nid
	 *            ID
	 */
	public void setNid(Long nid) {
		this.nid = nid;
	}

	/**
	 * Get the ID.
	 * 
	 * @return ID
	 */
	public Long getNid() {
		return this.nid;
	}

	/**
	 * Set the 公司.
	 * 
	 * @param company
	 *            公司
	 */
	public void setCompany(Company company) {
		this.company = company;
	}

	/**
	 * Get the 公司.
	 * 
	 * @return 公司
	 */
	public Company getCompany() {
		return this.company;
	}

	/**
	 * Set the 标题.
	 * 
	 * @param title
	 *            标题
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * Get the 标题.
	 * 
	 * @return 标题
	 */
	public String getTitle() {
		return this.title;
	}

	/**
	 * Set the description.
	 * 
	 * @param description
	 *            description
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * Get the description.
	 * 
	 * @return description
	 */
	public String getDescription() {
		return this.description;
	}

	/**
	 * Set the 创建日期.
	 * 
	 * @param createTime
	 *            创建日期
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * Get the 创建日期.
	 * 
	 * @return 创建日期
	 */
	public Date getCreateTime() {
		return this.createTime;
	}

	/**
	 * Set the 更新日期.
	 * 
	 * @param updateTime
	 *            更新日期
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * Get the 更新日期.
	 * 
	 * @return 更新日期
	 */
	public Date getUpdateTime() {
		return this.updateTime;
	}

	/**
	 * Set the set of the 新闻详细表.
	 * 
	 * @param newsinfoSet
	 *            The set of 新闻详细表
	 */
	public void setNewsinfoSet(Set<Newsinfo> newsinfoSet) {
		this.newsinfoSet = newsinfoSet;
	}

	/**
	 * Add the 新闻详细表.
	 * 
	 * @param newsinfo
	 *            新闻详细表
	 */
	public void addNewsinfo(Newsinfo newsinfo) {
		this.newsinfoSet.add(newsinfo);
	}

	/**
	 * Get the set of the 新闻详细表.
	 * 
	 * @return The set of 新闻详细表
	 */
	public Set<Newsinfo> getNewsinfoSet() {
		return this.newsinfoSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((nid == null) ? 0 : nid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		News other = (News) obj;
		if (nid == null) {
			if (other.nid != null) {
				return false;
			}
		} else if (!nid.equals(other.nid)) {
			return false;
		}
		return true;
	}

}
