package com.lxzl.db.bean;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of 合作伙伴表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Partners implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID. */
	private Long pid;

	/** 公司. */
	private Company company;

	/** 名称. */
	private String name;

	/** 描述. */
	private String description;

	/** 创建日期. */
	private Date createTime;

	/** 更新日期. */
	private Date updateTime;

	/** The set of 合作伙伴信息表. */
	private Set<Partnerinfo> partnerinfoSet;

	/**
	 * Constructor.
	 */
	public Partners() {
		this.partnerinfoSet = new HashSet<Partnerinfo>();
	}

	/**
	 * Set the ID.
	 * 
	 * @param pid
	 *            ID
	 */
	public void setPid(Long pid) {
		this.pid = pid;
	}

	/**
	 * Get the ID.
	 * 
	 * @return ID
	 */
	public Long getPid() {
		return this.pid;
	}

	/**
	 * Set the 公司.
	 * 
	 * @param company
	 *            公司
	 */
	public void setCompany(Company company) {
		this.company = company;
	}

	/**
	 * Get the 公司.
	 * 
	 * @return 公司
	 */
	public Company getCompany() {
		return this.company;
	}

	/**
	 * Set the 名称.
	 * 
	 * @param name
	 *            名称
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get the 名称.
	 * 
	 * @return 名称
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Set the 描述.
	 * 
	 * @param description
	 *            描述
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * Get the 描述.
	 * 
	 * @return 描述
	 */
	public String getDescription() {
		return this.description;
	}

	/**
	 * Set the 创建日期.
	 * 
	 * @param createTime
	 *            创建日期
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * Get the 创建日期.
	 * 
	 * @return 创建日期
	 */
	public Date getCreateTime() {
		return this.createTime;
	}

	/**
	 * Set the 更新日期.
	 * 
	 * @param updateTime
	 *            更新日期
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * Get the 更新日期.
	 * 
	 * @return 更新日期
	 */
	public Date getUpdateTime() {
		return this.updateTime;
	}

	/**
	 * Set the set of the 合作伙伴信息表.
	 * 
	 * @param partnerinfoSet
	 *            The set of 合作伙伴信息表
	 */
	public void setPartnerinfoSet(Set<Partnerinfo> partnerinfoSet) {
		this.partnerinfoSet = partnerinfoSet;
	}

	/**
	 * Add the 合作伙伴信息表.
	 * 
	 * @param partnerinfo
	 *            合作伙伴信息表
	 */
	public void addPartnerinfo(Partnerinfo partnerinfo) {
		this.partnerinfoSet.add(partnerinfo);
	}

	/**
	 * Get the set of the 合作伙伴信息表.
	 * 
	 * @return The set of 合作伙伴信息表
	 */
	public Set<Partnerinfo> getPartnerinfoSet() {
		return this.partnerinfoSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((pid == null) ? 0 : pid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Partners other = (Partners) obj;
		if (pid == null) {
			if (other.pid != null) {
				return false;
			}
		} else if (!pid.equals(other.pid)) {
			return false;
		}
		return true;
	}

}
