package com.lxzl.db.bean;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of 产品详细.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Productinfo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID. */
	private Long piid;

	/** 产品. */
	private Product product;

	/** 图片路径. */
	private String imgUrl;

	/** 创建日期. */
	private Date createTime;

	/** 更新日期. */
	private Date updateTime;

	/**
	 * Constructor.
	 */
	public Productinfo() {
	}

	/**
	 * Set the ID.
	 * 
	 * @param piid
	 *            ID
	 */
	public void setPiid(Long piid) {
		this.piid = piid;
	}

	/**
	 * Get the ID.
	 * 
	 * @return ID
	 */
	public Long getPiid() {
		return this.piid;
	}

	/**
	 * Set the 产品.
	 * 
	 * @param product
	 *            产品
	 */
	public void setProduct(Product product) {
		this.product = product;
	}

	/**
	 * Get the 产品.
	 * 
	 * @return 产品
	 */
	public Product getProduct() {
		return this.product;
	}

	/**
	 * Set the 图片路径.
	 * 
	 * @param imgUrl
	 *            图片路径
	 */
	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}

	/**
	 * Get the 图片路径.
	 * 
	 * @return 图片路径
	 */
	public String getImgUrl() {
		return this.imgUrl;
	}

	/**
	 * Set the 创建日期.
	 * 
	 * @param createTime
	 *            创建日期
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * Get the 创建日期.
	 * 
	 * @return 创建日期
	 */
	public Date getCreateTime() {
		return this.createTime;
	}

	/**
	 * Set the 更新日期.
	 * 
	 * @param updateTime
	 *            更新日期
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * Get the 更新日期.
	 * 
	 * @return 更新日期
	 */
	public Date getUpdateTime() {
		return this.updateTime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((piid == null) ? 0 : piid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Productinfo other = (Productinfo) obj;
		if (piid == null) {
			if (other.piid != null) {
				return false;
			}
		} else if (!piid.equals(other.piid)) {
			return false;
		}
		return true;
	}

}
